### ISSUE TITLE
Scrolling: "Jump to first unread message" / Read Marker is really annoying

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-meta#1418]
Annoyances:
 - Having an RM for public rooms that I probably don't want to read every message of is annoying because I end up clicking the "X" every time to claim back my screen real-estate. Solutions are 1. and 2.
 - Skim-reading is very frustrating because you have to scroll down, scroll up to catch the RM, scroll down...

I think we should consider the following improvements:
 1. Per-room setting for disabling the RM entirely. This would hide the RM but under the hood set it to the RR.
 1. Disable the RM for public rooms by default. Or provide a global setting to disable/enable it when you first join.
 1. Make it easier to skim-read: update a local RM much more frequently and then debounce the setting of the server-side RM so as not to suffer from rate-limiting instead of tying the server-side rate limiting avoidance strategy to the UI.

**Comment by cmurf** [comment]
Just like with tagged/labeled/sorted emails, sometimes I care about whether there are unread messages and sometimes I don't. I think "track unread" (or not), or "track mentions" (or not) per room might need consideration. My most active rooms, I don't even care about unread as much as I care about getting to the "most recent unread mention of my name or a keyword". Of course that also brings about per room keywords...

**Comment by Tectract** [comment]
Personally, I NEVER want which messages I have read to be tracked. I view it as a huge privacy violation. I never want notifications about unread messages in ANY chat room, and I would prefer if people are NOT ALLOWED to tag me, for any reason, ever. I just want to chat. I don't want notifications. No means no.

**Comment by Lamdarer** [comment]
> Personally, I NEVER want which messages I have read to be tracked. I view it as a huge privacy violation.

See: https://github.com/vector-im/element-web/issues/2527
Should be fixed soon

**Comment by Tectract** [comment]
Slowly people are seeing the light. "unread message" means "I am tracking everything you look at.". It's a MAJOR PRIVACY VIOLATION!!!

**Comment by jivanpal** [comment]
@Tectract You don't need to keep repeating the same thing with different amounts of emphasis. We get it.

> I just want to chat. I don't want notifications.

You can toggle ping notifications on a per-room basis.

**Comment by Tectract** [comment]
It's true that it is now possible to turn off ping notifications per room, however this doesn't solve the problem. Slack still tracks which messages I am reading and sends me "unread message" notifications. 

You don't seem to get it. What I want is for Slack to stop tracking which messages I have read, COMPLETELY FOREVER IN ALL ROOMS. What I want is my PRIVACY back.

**Comment by natrius** [comment]
Please, don't get me wrong, but... please stop commenting here. You have absolutely no technical clue how something could work and yet you demand(!) stuff without even asking before. 
Another think: Why should we care about anything that **Slack** does? This Github Repo has nothing to do with Slack.

Still, i try to explain: The unread messages has NOTHING to do with a server. Thats your client doing that and its not tracking anything to be able to do something like that. So you have your privacy back and you can stop commenting here with stuff completely irrelevant for this issue. 

Furthermore: Set up your own server and set `use_presence = false` and nobody can track anything. So there even exists a solution to your imagined privacy-violation.

**Comment by Tectract** [comment]
Natrius, you are being super-rude. This is not your repo so I don't appreciate your gatekeeping. This thread is about disabling the "unread message" notification, you are going on and on about "ping" notifications, which is a separate issue.

> You have absolutely no technical clue how something could work and yet you demand(!) stuff without even asking before.

Brother I probably got my degree in computer engineering while you were in gradeschool, these types of unwarranted insults don't belong here.

> use_presence = false

Would that stop the server from tracking me? Where do I put that?  It should be a default.

**Comment by jivanpal** [comment]
@Tectract 

> It's true that it is now possible to turn off ping notifications per room, however this doesn't solve the problem.

You mentioned two problems:

1. Element sends read receipts, but you don't want it to.
2. Element gives you notifications, but you don't want it to.

Problem (1) is described by vector-im/element-web#2527 and now solved in the client API/SDK, just needs to make its way to the client proper. Problem (2) is solved in notification settings.

Neither of those problems is the subject of this GitHub issue, so if you have questions or suggestions/requests concerning them (such as your desire for sending read receipts to be disabled by default), please do so in the relevant issue thread or open a new one. This is not the place for it; this issue thread only concerns the UI feature mentioned in the title.
